// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mystays.TripAdvisor.Business.Database;

namespace Mystays.TripAdvisor.Business.Migrations
{
    [DbContext(typeof(MystaysContext))]
    partial class MystaysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mystays.TripAdvisor.Business.Database.Models.Activity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName");

                    b.Property<int?>("Language_ID");

                    b.Property<string>("LocalName");

                    b.Property<int?>("Location_ID");

                    b.HasKey("ID");

                    b.HasIndex("Language_ID");

                    b.HasIndex("Location_ID");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("Mystays.TripAdvisor.Business.Database.Models.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageCode");

                    b.HasKey("ID");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Mystays.TripAdvisor.Business.Database.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("LocationName");

                    b.Property<int>("Location_ID");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Mystays.TripAdvisor.Business.Database.Models.Activity", b =>
                {
                    b.HasOne("Mystays.TripAdvisor.Business.Database.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("Language_ID");

                    b.HasOne("Mystays.TripAdvisor.Business.Database.Models.Location", "Location")
                        .WithMany("Activities")
                        .HasForeignKey("Location_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
